// Package daemon runs the xMustard API as a per-user service (WS-58, PAR-RT-03): the
// launchd agent or systemd user units that `xmustard-ops setup` installs, the health
// probe setup waits on, systemd socket activation, and the size-capped log file the
// daemon writes.
//
// Units run the API on the loopback interface only, restart it when it crashes (not
// when it is stopped), and carry no credential: tokens live hashed in the data dir,
// and a service's environment is inherited by everything the daemon starts, agents
// included, so the approver and bearer tokens never enter it (WS-57).
package daemon

import (
	"fmt"
	"net"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"unicode"
)

// Marker is written into every unit this package renders. Setup replaces and
// uninstall removes only files that carry it, so a hand-written unit (an evaluation
// stack, another tool's agent) is never touched.
const Marker = "generated by xmustard-ops setup"

// LoopbackHost is the only address a unit binds.
const LoopbackHost = "127.0.0.1"

// SecretEnv names the credentials a unit must never carry and that systemd strips
// from the environment its user manager would otherwise pass on.
var SecretEnv = []string{"XMUSTARD_APPROVER_TOKEN", "XMUSTARD_API_TOKEN", "XMUSTARD_TOKEN", "XMUSTARD_AUTH_TOKENS"}

// secretKeyParts refuse an extra variable whose name looks like a credential.
var secretKeyParts = []string{"TOKEN", "SECRET", "PASSWORD", "PASSWD", "CREDENTIAL", "APIKEY", "API_KEY", "PRIVATE_KEY", "DSN"}

var (
	labelPattern  = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$`)
	envKeyPattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)
)

// Spec is one installation of the daemon.
type Spec struct {
	Label   string // the launchd label or systemd unit name
	UnitDir string // where the unit files go
	APIBin  string // absolute path of xmustard-api
	CoreBin string // absolute path of xmustard-core; "" leaves it to PATH
	DataDir string
	LogFile string
	Port    int
	Path    string            // PATH for the daemon (git, the core)
	Env     map[string]string // extra variables; credentials are refused
}

// Validate checks everything a unit file carries. A label becomes a file name; paths
// must be absolute and free of quotes and backslashes (systemd refuses them in an
// executable path, and no path needs them); nothing may hold a control character,
// which no unit format can carry safely.
func (s Spec) Validate() error {
	if !labelPattern.MatchString(s.Label) {
		return fmt.Errorf("label %q: use letters, digits, '.', '_' or '-' (at most 100)", s.Label)
	}
	for _, p := range []struct {
		name, value string
		optional    bool
	}{
		{"unit dir", s.UnitDir, false}, {"api binary", s.APIBin, false}, {"core binary", s.CoreBin, true},
		{"data dir", s.DataDir, false}, {"log file", s.LogFile, false},
	} {
		if p.value == "" && p.optional {
			continue
		}
		if !filepath.IsAbs(p.value) {
			return fmt.Errorf("%s %q must be an absolute path", p.name, p.value)
		}
		if err := plain(p.name, p.value); err != nil {
			return err
		}
		if strings.ContainsAny(p.value, `"'\`) {
			return fmt.Errorf("%s %q contains a quote or a backslash, which a unit file cannot carry safely", p.name, p.value)
		}
	}
	if s.Port < 1 || s.Port > 65535 {
		return fmt.Errorf("port %d is out of range", s.Port)
	}
	if err := plain("PATH", s.Path); err != nil {
		return err
	}
	fixed := s.fixedEnv()
	for k, v := range s.Env {
		if !envKeyPattern.MatchString(k) {
			return fmt.Errorf("environment name %q is not a variable name", k)
		}
		if IsSecretKey(k) {
			return fmt.Errorf("refusing %s in the unit's environment: a service passes its environment to every process it starts, so credentials stay out of it (mint tokens into the data dir instead)", k)
		}
		if _, ok := fixed[k]; ok {
			return fmt.Errorf("%s is set by setup itself; use its flag", k)
		}
		if err := plain(k, v); err != nil {
			return err
		}
	}
	return nil
}

// IsSecretKey reports whether an environment variable name looks like a credential.
func IsSecretKey(k string) bool {
	up := strings.ToUpper(k)
	return slices.Contains(SecretEnv, up) || slices.ContainsFunc(secretKeyParts, func(p string) bool { return strings.Contains(up, p) })
}

func plain(name, v string) error {
	if strings.IndexFunc(v, unicode.IsControl) >= 0 {
		return fmt.Errorf("%s contains a control character", name)
	}
	return nil
}

// fixedEnv is what setup itself sets.
func (s Spec) fixedEnv() map[string]string {
	m := map[string]string{
		"XMUSTARD_DATA_DIR": s.DataDir,
		"XMUSTARD_API_HOST": LoopbackHost,
		"XMUSTARD_API_PORT": strconv.Itoa(s.Port),
		"XMUSTARD_LOG_FILE": s.LogFile,
	}
	if s.CoreBin != "" {
		m["XMUSTARD_CORE_BIN"] = s.CoreBin
	}
	if s.Path != "" {
		m["PATH"] = s.Path
	}
	return m
}

// EnvVar is one variable of a unit's environment.
type EnvVar struct{ Key, Value string }

// Environ is the unit's environment sorted by name: setup's settings plus Env.
func (s Spec) Environ() []EnvVar {
	m := s.fixedEnv()
	for k, v := range s.Env {
		m[k] = v
	}
	out := make([]EnvVar, 0, len(m))
	for k, v := range m {
		out = append(out, EnvVar{k, v})
	}
	slices.SortFunc(out, func(a, b EnvVar) int { return strings.Compare(a.Key, b.Key) })
	return out
}

// BaseURL is where the daemon answers.
func (s Spec) BaseURL() string {
	return "http://" + net.JoinHostPort(LoopbackHost, strconv.Itoa(s.Port))
}

// SearchPath is the PATH a unit gives the daemon: the directories of its binaries,
// then the absolute entries of the installing user's PATH (a relative entry would
// resolve against the daemon's working directory), without repeats.
func SearchPath(userPath string, binDirs ...string) string {
	var dirs []string
	for _, d := range append(binDirs, filepath.SplitList(userPath)...) {
		if d != "" && filepath.IsAbs(d) && !slices.Contains(dirs, d) {
			dirs = append(dirs, d)
		}
	}
	return strings.Join(dirs, string(filepath.ListSeparator))
}
