package main

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	gateDocBegin = "<!-- route-gates:begin (generated by TestSecurityDocRouteGateTable; XMUSTARD_UPDATE_DOCS=1 rewrites it) -->"
	gateDocEnd   = "<!-- route-gates:end -->"
)

// renderGateTable renders routeGateTable as the Markdown table docs/SECURITY.md carries.
func renderGateTable() string {
	var b strings.Builder
	b.WriteString("| Route | Profile | Role | Read-only mode | Tool | Note |\n|---|---|---|---|---|---|\n")
	for _, pattern := range sortedGatePatterns() {
		g := routeGateTable[pattern]
		profile := "platform"
		if g.Core {
			profile = "core"
		}
		ro := "served"
		if g.mutating(pattern) {
			ro = "refused"
		}
		method := patternMethod(pattern)
		if method == "" {
			method = "ANY"
		}
		b.WriteString("| `" + method + " " + patternPath(pattern) + "` | " + profile + " | " + g.Role + " | " + ro + " | " + g.Tool + " | " + g.Note + " |\n")
	}
	return b.String()
}

// docs/SECURITY.md documents the route gate table; this keeps it generated from the
// code, the single source of truth.
func TestSecurityDocRouteGateTable(t *testing.T) {
	path := filepath.Join("..", "..", "..", "docs", "SECURITY.md")
	raw, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("docs/SECURITY.md not present in this checkout")
	}
	if err != nil {
		t.Fatal(err)
	}
	doc := string(raw)
	begin, end := strings.Index(doc, gateDocBegin), strings.Index(doc, gateDocEnd)
	if begin < 0 || end < begin {
		t.Fatalf("docs/SECURITY.md lacks the route-gates markers")
	}
	want := doc[:begin+len(gateDocBegin)] + "\n" + renderGateTable() + doc[end:]
	if want == doc {
		return
	}
	if os.Getenv("XMUSTARD_UPDATE_DOCS") == "1" {
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	t.Fatalf("docs/SECURITY.md route gate table is stale; run XMUSTARD_UPDATE_DOCS=1 go test ./cmd/xmustard-api -run TestSecurityDocRouteGateTable")
}
